import {supabase,esc} from "./app.js";
const auth=document.querySelector("#auth"),panel=document.querySelector("#panel"),status=document.querySelector("#status");
async function boot(){
 const {data:{session}}=await supabase.auth.getSession();
 if(!session){showLogin();return}
 panel.hidden=false;auth.innerHTML=`<p>Signed in as ${esc(session.user.email)} <button id="logout" class="btn ghost">Log out</button></p>`;document.querySelector("#logout").onclick=()=>supabase.auth.signOut().then(()=>location.reload());load();
}
function showLogin(){auth.innerHTML=`<form id="login" class="form"><h1>Admin login</h1><label>Email<input name="email" type="email" required></label><label>Password<input name="password" type="password" required></label><button class="btn">Sign in</button><p id="loginMsg"></p></form>`;document.querySelector("#login").onsubmit=async e=>{e.preventDefault();const d=new FormData(e.target);const {error}=await supabase.auth.signInWithPassword({email:d.get("email"),password:d.get("password")});if(error)document.querySelector("#loginMsg").textContent=error.message;else location.reload()}}
async function load(){const {data}=await supabase.from("videos").select("*").order("created_at",{ascending:false});document.querySelector("#manage").innerHTML=(data||[]).map(v=>`<div class="manage"><strong>${esc(v.title)}</strong><span>${v.published?"Published":"Hidden"}</span><button data-edit="${v.id}" class="btn ghost">Edit</button><button data-id="${v.id}" data-p="${v.published}" class="btn ghost">${v.published?"Unpublish":"Publish"}</button><button data-del="${v.id}" class="btn danger">Delete</button></div>`).join("");document.querySelectorAll("[data-edit]").forEach(b=>b.onclick=async()=>{const id=b.dataset.edit;const {data:v,error}=await supabase.from("videos").select("*").eq("id",id).single();if(error||!v){alert("Could not load video");return}const title=prompt("Title",v.title);if(title===null)return;const category=prompt("Category",v.category);if(category===null)return;const description=prompt("Description",v.description||"");if(description===null)return;const {error:ue}=await supabase.from("videos").update({title,category,description}).eq("id",id);if(ue)alert(ue.message);else load()});document.querySelectorAll("[data-id]").forEach(b=>b.onclick=async()=>{await supabase.from("videos").update({published:b.dataset.p!=="true"}).eq("id",b.dataset.id);load()});document.querySelectorAll("[data-del]").forEach(b=>b.onclick=async()=>{if(confirm("Delete this record?")){await supabase.from("videos").delete().eq("id",b.dataset.del);load()}})}
document.querySelector("#upload").onsubmit=async e=>{e.preventDefault();status.textContent="Uploading...";const d=new FormData(e.target),video=d.get("video"),thumb=d.get("thumb"),id=crypto.randomUUID(),base=`${id}-${Date.now()}`;
 const vr=await supabase.storage.from("videos").upload(`${base}-${video.name}`,video,{contentType:video.type,upsert:false}); if(vr.error){status.textContent=vr.error.message;return}
 let thumbUrl="";if(thumb?.size){const tr=await supabase.storage.from("thumbnails").upload(`${base}-${thumb.name}`,thumb,{contentType:thumb.type});if(!tr.error)thumbUrl=supabase.storage.from("thumbnails").getPublicUrl(tr.data.path).data.publicUrl}
 const vu=supabase.storage.from("videos").getPublicUrl(vr.data.path).data.publicUrl;
 const {error}=await supabase.from("videos").insert({id,title:d.get("title"),category:d.get("category"),description:d.get("description"),video_url:vu,thumbnail_url:thumbUrl,published:true});
 status.textContent=error?error.message:"Uploaded and published.";if(!error){e.target.reset();load()}
};
boot();