-- DesiVexa social features
-- Run this in Supabase Dashboard -> SQL Editor.

create table if not exists public.video_likes (
  id bigint generated by default as identity primary key,
  video_id uuid not null references public.videos(id) on delete cascade,
  visitor_id text not null,
  created_at timestamptz not null default now(),
  unique(video_id, visitor_id)
);

create table if not exists public.video_comments (
  id bigint generated by default as identity primary key,
  video_id uuid not null references public.videos(id) on delete cascade,
  visitor_id text not null,
  display_name text not null default 'User',
  body text not null,
  approved boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.video_likes enable row level security;
alter table public.video_comments enable row level security;

drop policy if exists "public can read likes" on public.video_likes;
drop policy if exists "public can create likes" on public.video_likes;
drop policy if exists "public can delete own visitor like" on public.video_likes;
create policy "public can read likes" on public.video_likes for select to anon, authenticated using (true);
create policy "public can create likes" on public.video_likes for insert to anon, authenticated with check (length(visitor_id) between 20 and 100);
create policy "public can delete own visitor like" on public.video_likes for delete to anon, authenticated using (length(visitor_id) between 20 and 100);

drop policy if exists "public can read approved comments" on public.video_comments;
drop policy if exists "public can submit comments" on public.video_comments;
create policy "public can read approved comments" on public.video_comments for select to anon, authenticated using (approved = true);
create policy "public can submit comments" on public.video_comments for insert to anon, authenticated with check (length(visitor_id) between 20 and 100 and length(body) between 1 and 2000 and length(display_name) between 1 and 60 and approved = false);

create index if not exists video_likes_video_id_idx on public.video_likes(video_id);
create index if not exists video_comments_video_id_idx on public.video_comments(video_id, created_at desc);
